# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9f02784eb0a802350ee76c618b76c84f69bd8eda6d10be7332d9da9c73515436b67a34cdbdaa07bd77fee132c0f6c1e104d7ad5d77fdb45102eb9b978b9ca82

test:
  secret_key_base: b6e36177ccb1c5b63b52e4f89276a3b6dbc00f71d292c68a168c574ebf5856bc7e87328a4a113f43f73219da0f5a14eeb3d7a7f7657d78c624e1223f1db75c5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
